version: "3"
services:
  influx:
    image: influxdb:alpine
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=lpwan-handson
      - DOCKER_INFLUXDB_INIT_ORG=lpwan
      - DOCKER_INFLUXDB_INIT_BUCKET=lpwan
    volumes:
      - influx-config:/etc/influxdb2
      - influx-data:/var/lib/influxdb2
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  nodered:
    image: nodered/node-red
    ports:
      - 1880:1880
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - node_red_data:/data
volumes:
  influx-config:
  influx-data:
  node_red_data:
    driver_opts:
      uid: 0
      gid: 0